# This is a basic workflow to help you get started with Actions
name: Tests with BTC EmbeddedPlatform

# Controls when the workflow will run
on: [ push ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: run test workflow
        run:  python workflow.py ${env:GITHUB_WORKSPACE}
